# Generated by Django 4.2.9 on 2026-03-29 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('tech_stack', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('LOOKING_FOR_TEAMMATES', 'Looking For Teammates'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ACTIVE', 'Active')], default='LOOKING_FOR_TEAMMATES', max_length=25)),
                ('team_member_count', models.IntegerField(default=0)),
                ('team_capacity', models.IntegerField(default=0)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('bookmarked_by', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='teams.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
