# Generated by Django 4.2.9 on 2026-04-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sync_usernames_to_primary_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admission_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
