# Generated by Django 4.2.9 on 2026-03-29 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PROJECT_INVITE', 'Project Invite'), ('TEAM_INVITE', 'Team Invite'), ('JOIN_REQUEST', 'Join Request'), ('JOIN_APPROVED', 'Join Approved'), ('JOIN_REJECTED', 'Join Rejected'), ('TEAM_UPDATE', 'Team Update'), ('PROJECT_UPDATE', 'Project Update'), ('EVENT_REMINDER', 'Event Reminder'), ('MESSAGE', 'Message')], max_length=25)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_id', models.CharField(blank=True, max_length=255, null=True)),
                ('related_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx')],
            },
        ),
    ]
